### ISSUE TITLE
Transaction button not working

### ISSUE THREAD

**Issue by ROWHSEGOY** [NujanSitaula/AgricultureManagementSystem#11]
On farmer panel when you simultaneously click on transaction button after invoice on nav bar it dosen't get clicked. But, when click on market place and now click on Transaction, the transaction will get clicked. Developers fix this issue asap.
![image](https://user-images.githubusercontent.com/87907563/168804831-adc53fd7-3a4d-4119-ba03-0c37df5d511b.png)

**Comment by NujanSitaula** [comment]
Issue has been resolved on last update.
